routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {

    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');

    Route::resource('company', 'Company\CompanyController');

    Route::get('offline/index', 'UserOffController@index')->name('offline.index');
    Route::get('offline/restore/{id}', 'UserOffController@restore')->name('offline.restore');

    //Media
    Route::get('music', 'Media\MusicController@index')->name('music.index');
    Route::get('music/create', 'Media\MusicController@create')->name('music.create');
    Route::get('music/{id}', 'Media\MusicController@show')->name('music.show');
    Route::post('music', 'Media\MusicController@store')->name('music.store');
    Route::delete('music/{id}', 'Media\MusicController@delete')->name('music.delete');

    Route::get('playlist/index/{id}', 'Media\MusicController@playlistIndex')->name('playlist.index');
    Route::get('playlist/create', 'Media\MusicController@playlistCreate')->name('playlist.create');
    Route::get('playlist/{id}/edit', 'Media\MusicController@playlistEdit')->name('playlist.edit');
    Route::post('playlist', 'Media\MusicController@playlistStore')->name('playlist.store');
    Route::put('playlist/{id}', 'Media\MusicController@playlistUpdate')->name('playlist.update');
    Route::get('playlist/show/{id}', 'Media\MusicController@playlistShow')->name('playlist.show');
    Route::delete('playlist/destroy/{id}', 'Media\MusicController@playlistDestroy')->name('playlist.destroy');
    Route::delete('playlist/item/{id}', 'Media\MusicController@itemDestroy')->name('playlist.delete');
    //Arcevo gênero
    Route::get('heap', 'Media\HeapController@index')->name('heap.index');
    Route::get('heap/create', 'Media\HeapController@create')->name('heap.create');
    Route::post('heap', 'Media\HeapController@store')->name('heap.store');
    Route::get('heap/{id}', 'Media\HeapController@show')->name('heap.show');

    //product
    Route::get('product', 'Product\ProductController@index')->name('product.index');
    Route::get('product/create', 'Product\ProductController@create')->name('product.create');
    Route::post('product', 'Product\ProductController@store')->name('product.store');
    Route::get('product/{id}', 'Product\ProductController@show')->name('product.show');
    Route::get('product/{id}/edit', 'Product\ProductController@edit')->name('product.edit');
    Route::put('product/{id}', 'Product\ProductController@update')->name('product.update');
    Route::delete('product/{id}', 'Product\ProductController@destroy')->name('product.destroy');

    Route::post('product/like/{id}', 'Product\ProductController@like')->name('product.like');
    Route::post('product/view/{id}', 'Product\ProductController@view')->name('product.view');

    Route::post('comment/create/{id}', 'Product\ProductController@comment')->name('comment.create');
    Route::get('comment/{id}/edit', 'Product\ProductController@commentEdit')->name('comment.edit');
    Route::put('comment/{id}', 'Product\ProductController@commentUpdate')->name('comment.update');
    Route::delete('comment/{id}', 'Product\ProductController@commentDestroy')->name('comment.destroy');

    Route::get('content', 'Content\ContentController@index')->name('content.index');
    Route::get('content/create', 'Content\ContentController@create')->name('content.create');
    Route::post('content', 'Content\ContentController@store')->name('content.store');
    Route::delete('content/{id}', 'Content\ContentController@destroy')->name('content.destroy');
});

app/Models/Company/Address.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Model;
use App\Models\Company\Company;

class Address extends Model
{
    protected $fillable = [
        'public_place','number','cep','complement','district','county','uf'
    ];

    public function company()
    {
        return $this->belongsTo(Comapny::class);
    }
}

app/Models/Company/Company.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;


class Company extends Model
{
    protected $fillable = [
        'registration_number', 'business_name', 'fantasy_name',
    ];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function address()
    {
        return $this->hasOne(Address::class);
    }

    public function contact()
    {
        return $this->hasOne(Contact::class);
    }

    public function term()
    {
        return $this->hasOne(Term::class);
    }
}

app/Models/Company/Contact.php
<?php

namespace App\Models\Company;


use Illuminate\Database\Eloquent\Model;
use App\Models\Company\Company;

class Contact extends Model
{
    protected $fillable = [
        'email','phone1','phone2'
    ];

    public function company()
    {
        return $this->belongsTo(Comapny::class);
    }
}

app/Models/Company/Segment.php
<?php

namespace App\Models\Company;

use App\Models\Content\Content;
use Illuminate\Database\Eloquent\Model;

class Segment extends Model
{
    public function term()
    {
        return $this->hasMany(Term::class);
    }

    public function content()
    {
        return $this->hasOne(Content::class);
    }
}

app/Models/Company/Term.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Model;

class Term extends Model
{
    protected $fillable = ['terms_and_conditions'];

    public function company()
    {
        return $this->belongsTo(Comapny::class);
    }

    public function segment()
    {
        return $this->belongsTo(Segment::class);
    }
}

app/Http/Controllers/Api/Company/CompanyController.php
<?php

namespace App\Http\Controllers\Api\Company;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Company\Company;
use App\Models\Company\Address;
use Illuminate\Support\Facades\Validator;
use App\Models\Company\Contact;
use App\Models\Company\Segment;
use App\Models\Company\Term;

class CompanyController extends Controller
{
    public function index()
    {
        $id = Auth::id();

        $company =  Company::where('user_id', $id)->with('user', 'address', 'contact', 'term.segment')->get();

        return response()->json($company);
    }

    public function segment()
    {
        $segments = Segment::all();
        return response()->json($segments);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'registration_number' => 'required',
            'business_name' => 'required',
            'fantasy_name' => 'required',
            'public_place' => 'required',
            'number' => 'required',
            'uf' => 'required',
            'cep' => 'required',
            'district' => 'required',
            'county' => 'required',
            'email' => 'required',
            'phone1' => 'required',
            'segment' => 'required',
            'terms_and_conditions' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json($validator->errors()->toJson(), 400);
        }

        $id = Auth::id();

        $company = new Company();
        $company->registration_number = $request->registration_number;
        $company->business_name = $request->business_name;
        $company->fantasy_name = $request->fantasy_name;
        $company->user_id = $id;
        $company->save();

        $address = new Address();
        $address->public_place = $request->public_place;
        $address->number = $request->number;
        $address->uf = $request->uf;
        $address->complement = $request->complement;
        $address->cep = $request->cep;
        $address->district = $request->district;
        $address->county = $request->county;
        $address->company_id = $company->id;
        $address->save();

        $contact = new Contact();
        $contact->email = $request->email;
        $contact->phone1 = $request->phone1;
        $contact->phone2 = $request->phone2;
        $contact->company_id = $company->id;
        $contact->save();

        $term = new Term();
        $term->terms_and_conditions = $request->terms_and_conditions;
        $term->company_id = $company->id;
        $term->segment_id = $request->segment;
        $term->save();

        return response()->json([
            'message' => 'User successfully registered'
        ], 200);
    }

    public function show($id)
    {
        $company = Company::find($id);
        $company->load('address', 'contact');


        return response()->json($company);
    }

    public function update(Request $request, $id)
    {
        $company = Company::find($id);

        $company->registration_number = $request->registration_number;
        $company->business_name = $request->business_name;
        $company->fantasy_name = $request->fantasy_name;
        $company->address->public_place = $request->public_place;
        $company->address->number = $request->number;
        $company->address->uf = $request->uf;
        $company->address->complement = $request->complement;
        $company->address->cep = $request->cep;
        $company->address->district = $request->district;
        $company->address->county = $request->county;
        $company->contact->email = $request->email;
        $company->contact->phone1 = $request->phone1;
        $company->contact->phone2 = $request->phone2;

        $company->push();

        return response()->json([
            'message' => 'Information changed successfully'
        ], 201);
    }

    public function destroy($id)
    {
        $company = Company::findOrFail($id);

        $company->delete();

        return response()->json([
            'message' => 'Information deleted successfully'
        ], 201);
    }
}

app/Http/Controllers/Company/CompanyController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Company\Company;
use App\Models\Company\Address;
use App\Models\Company\Contact;
use App\Models\Company\Segment;
use App\Models\Company\Term;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::with('user','address','contact','term.segment')->get();
        return view('company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $segments = Segment::all();
        return view('company.create', compact('segments'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'registration_number' => 'required',
            'business_name' => 'required',
            'fantasy_name' => 'required',
            'public_place' => 'required',
            'number' => 'required',
            'uf' => 'required',
            'cep' => 'required',
            'district' => 'required',
            'county' => 'required',
            'email' => 'required',
            'phone1' => 'required',
            'segment' => 'required ',
            'term' => 'required '
        ]);

        $id = Auth::id();
        $company = new Company();
        $company->registration_number = $request->registration_number;
        $company->business_name = $request->business_name;
        $company->fantasy_name = $request->fantasy_name;
        $company->user_id = $id;
        $company->save();

        $address = new Address();
        $address->public_place = $request->public_place;
        $address->number = $request->number;
        $address->uf = $request->uf;
        $address->complement = $request->complement;
        $address->cep = $request->cep;
        $address->district = $request->district;
        $address->county = $request->county;
        $address->company_id = $company->id;
        $address->save();

        $contact = new Contact();
        $contact->email = $request->email;
        $contact->phone1 = $request->phone1;
        $contact->phone2 = $request->phone2;
        $contact->company_id = $company->id;
        $contact->save();

        $term = new Term();
        $term->terms_and_conditions = $request->term;
        $term->company_id = $company->id;
        $term->segment_id = $request->segment;
        $term->save();

        return redirect()->route('company.index')->with('success', 'Company created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);
        return view('company.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);

        $company->registration_number = $request->registration_number;
        $company->business_name = $request->business_name;
        $company->fantasy_name = $request->fantasy_name;
        $company->legal_nature_code = $request->legal_nature_code;
        $company->address->public_place = $request->public_place;
        $company->address->number = $request->number;
        $company->address->uf = $request->uf;
        $company->address->complement = $request->complement;
        $company->address->district = $request->district;
        $company->address->county = $request->county;
        $company->contact->email = $request->email;
        $company->contact->phone1 = $request->phone1;
        $company->contact->phone2 = $request->phone2;

        $company->push();

        return redirect()->route('company.index')->with('success', 'Company update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/company/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="container-fluid">
            <br>
            <div class="row">
                <div class="col-lg-6 margin-tb">
                    <div class="pull-left">
                        <h2>Register Company</h2>
                    </div>
                </div>
                <div class="col-lg-6 margin-tb">
                    <div class="pull-right">
                        @can('user-create')
                            <a class="btn btn-primary" href="{{ route('company.index') }}">Back</a>
                        @endcan
                    </div>
                </div>
            </div>

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <br>
            {{-- main --}}
            <form action=" {{ route('company.store') }} " method="POST">
                @csrf
                <div class="row">
                    <div class="col-3">
                        <label for="registration_number">CNPJ</label>
                        <input id="registration_number" class="form-control" type="text" name="registration_number" required
                            maxlength="14" size="10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <label for="business_name">Nome Empresarial</label>
                        <input id="business_name" class="form-control" type="text" name="business_name">
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <label for="fantasy_name">Nome Fantasia</label>
                        <input id="fantasy_name" class="form-control" type="text" name="fantasy_name">
                    </div>
                </div>
                <strong>Endereço</strong>
                <div class="row">
                    <div class="col-3">
                        <label for="cep">CEP</label>
                        <input id="cep" class="form-control" type="text" name="cep" required maxlength="8" size="10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <label for="public_place">Logradouro</label>
                        <input id="public_place" class="form-control" type="text" name="public_place">
                    </div>
                    <div class="col-2">
                        <label for="number">Nº</label>
                        <input id="number" class="form-control" type="text" name="number" required maxlength="6" size="10">
                    </div>
                    <div class="col-1">
                        <label for="uf">UF</label>
                        <input id="uf" class="form-control" type="text" name="uf" required maxlength="2" size="10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label for="complement">Complemento</label>
                        <input id="complement" class="form-control" type="text" name="complement">
                    </div>
                    <div class="col-2">
                        <label for="district">Bairro</label>
                        <input id="district" class="form-control" type="text" name="district">
                    </div>
                    <div class="col-2">
                        <label for="county">Cidade</label>
                        <input id="county" class="form-control" type="text" name="county">
                    </div>
                </div>
                <strong>Contatos</strong>
                <div class="row">
                    <div class="col-7">
                        <label for="email">Email</label>
                        <input id="email" class="form-control" type="email" name="email">
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <label for="phone1">Tel 1:.</label>
                        <input id="phone1" class="form-control" type="text" name="phone1" required maxlength="11" size="10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <label for="phone2">Tel 2:.</label>
                        <input id="phone2" class="form-control" type="text" name="phone2" required maxlength="11" size="10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <strong>Segmentos</strong>
                        <select name="segment" class="custom-select">
                            <option value="">Open this select menu</option>
                            @foreach ($segments as $segment)
                                <option value="{{ $segment->id }}">{{ $segment->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-7">
                        <br>
                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="term" value="true" id="invalidCheck" required>
                                <label class="form-check-label" for="invalidCheck">
                                    Agree to terms and conditions
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-7">
                        <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                </div>
            </form>
            {{-- finish --}}
        </div>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 margin-tb">
                <div class="pull-left">
                    <h2>Edit Company</h2>
                </div>
            </div>
            <div class="col-lg-6 margin-tb">
                <div class="pull-right">
                    @can('user-create')
                    <a class="btn btn-primary" href="{{ route('company.index') }}">Back</a>
                    @endcan
                </div>
            </div>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <br>
        <form action=" {{ route('company.update', $company->id) }} " method="POST">
            @csrf
            @method('PUT')
        <div class="row">
            <div class="col-3">
                <label for="registration_number">CNPJ</label>
                <input id="registration_number" class="form-control" type="text" name="registration_number" value=" {{$company->registration_number}} " required maxlength="14" size="10">
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <label for="business_name">Nome Empresarial</label>
                <input id="business_name" value=" {{$company->business_name}} " class="form-control" type="text" name="business_name">
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <label for="fantasy_name">Nome Fatasia</label>
                <input id="fantasy_name" class="form-control" type="text" value="{{$company->fantasy_name}}" name="fantasy_name">
            </div>
        </div>
        <strong>Endereço</strong>
        <div class="row">
            <div class="col-3">
                    <label for="cep">CEP</label>
                    <input id="cep" class="form-control" type="text" value="{{$company->address->cep}}" name="cep">
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <label for="public_place">Logradouro</label>
                <input id="public_place" class="form-control" type="text" value="{{$company->address->public_place}}" name="public_place">
            </div>
            <div class="col-2">
                <label for="number">Nº</label>
                <input id="number" class="form-control" type="text" value="{{$company->address->number}}" name="number" required maxlength="6" size="10">
            </div>
            <div class="col-1">
                <label for="uf">UF</label>
                <input id="uf" class="form-control" type="text" value="{{$company->address->uf}}" name="uf" required maxlength="2" size="10">
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <label for="complement">Complemento</label>
                <input id="complement" class="form-control" type="text" value="{{$company->address->complement}}" name="complement">
            </div>
            <div class="col-2">
                <label for="district">Bairro</label>
                <input id="district" class="form-control" type="text" value="{{$company->address->district}}" name="district">
            </div>
            <div class="col-2">
                <label for="county">Cidade</label>
                <input id="county" class="form-control" type="text" value="{{$company->address->county}}" name="county">
            </div>
        </div>
        <strong>Contatos</strong>
            <div class="row">
                <div class="col-7">
                    <label for="email">Email</label>
                    <input id="email" class="form-control" type="email" value="{{$company->contact->email}}" name="email">
                </div>
            </div>
            <div class="row">
                <div class="col-7">
                    <label for="phone1">Tel 1:.</label>
                    <input id="phone1" class="form-control" type="text" value="{{$company->contact->phone1}}" name="phone1" required maxlength="11" size="10">
                </div>
            </div>
        <div class="row">
            <div class="col-7">
                <label for="phone2">Tel 2:.</label>
                <input id="phone2" class="form-control" type="text" value="{{$company->contact->phone2}}" name="phone2" required maxlength="11" size="10">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-7">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
 </div>
</div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="container-fluid">
        <br>
        <div class="row">
            <div class="col-lg-6 margin-tb">
                <div class="pull-left">
                    <h2>Companies Manage</h2>
                </div>
            </div>
            <div class="col-lg-6 margin-tb">
                <div class="pull-right">
                    @can('user-create')
                    <a class="btn btn-success" href="{{ route('company.create') }}"> Create New Company</a>
                    @endcan
                </div>
            </div>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <br>
        {{--  main  --}}
        <div class="row">
            <div class="col">
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Company</th>
                        <th scope="col">CNPJ</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        @foreach ($companies as $company)
                            <td>{{$company->fantasy_name}}</td>
                            <td>{{$company->registration_number}}</td>
                            <td>
                                <a href="{{route('company.show', $company->id)}}" class="btn btn-info">Show</a>
                                <a href="{{route('company.edit', $company->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                        @endforeach
                      </tr>
                    </tbody>
                  </table>
            </div>
        </div>
        {{--  finish main  --}}
    </div>
</div>
@endsection